baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
paginate = 1

[params]
dateFormat = "Jan 2, 2006, 3:04PM"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4